// table.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SimpleTooltipDirective } from '../custom-tooltip-content';

@Component({
  selector: 'app-table',
  standalone: true,
  imports: [CommonModule, SimpleTooltipDirective],
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent {
  trades = [
    {
      tradeId: 'DRAFT/5746/22-07-2025',
      tradeDate: '16/07/2025',
      counterpartyCode: 'Green Technologies',
      buySell: 'BUY',
      commodity: 'Cocoa',
      grade: '-',
      contractTerm: '-',
      periodStartDate: '01/06/2025',
      periodEndDate: '30/06/2025',
      incoterm: 'FOB',
      loadLocation: 'ABU DHABI',
      unloadLocation: 'AFIA-ADABIYA',
      priceType: 'Fixed'
    },
    {
      tradeId: 'DRAFT/5740/22-07-2025',
      tradeDate: '17/07/2025',
      counterpartyCode: 'ANT EDIBLE OILS',
      buySell: 'BUY',
      commodity: 'CPL',
      grade: 'RCN-48',
      contractTerm: '-',
      periodStartDate: '17/07/2025',
      periodEndDate: '22/07/2025',
      incoterm: 'CFR',
      loadLocation: 'ABU DHABI',
      unloadLocation: 'ADEN',
      priceType: 'Fixed'
    },
    {
      tradeId: 'DRAFT/5739',
      tradeDate: '17/07/2025',
      counterpartyCode: 'TBD',
      buySell: 'SELL',
      commodity: 'Palm Oil',
      grade: 'A1',
      contractTerm: 'Short',
      periodStartDate: '20/07/2025',
      periodEndDate: '25/07/2025',
      incoterm: 'CIF',
      loadLocation: 'KANDLA',
      unloadLocation: 'MUMBAI',
      priceType: 'Floating'
    },
    
  {
    tradeId: "DRAFT/5740",
    tradeDate: "18/07/2025",
    counterpartyCode: "ACME001",
    buySell: "BUY",
    commodity: "Crude Oil",
    grade: "Brent",
    contractTerm: "Long",
    periodStartDate: "22/07/2025",
    periodEndDate: "30/08/2025",
    incoterm: "FOB",
    loadLocation: "SINGAPORE",
    unloadLocation: "CHENNAI",
    priceType: "Fixed"
  },
  {
    tradeId: "DRAFT/5741",
    tradeDate: "19/07/2025",
    counterpartyCode: "SHELL02",
    buySell: "SELL",
    commodity: "Natural Gas",
    grade: "Pipeline",
    contractTerm: "Medium",
    periodStartDate: "25/07/2025",
    periodEndDate: "15/09/2025",
    incoterm: "DDP",
    loadLocation: "HAZIRA",
    unloadLocation: "DELHI",
    priceType: "Floating"
  },
  {
    tradeId: "DRAFT/5742/22-07-2025",
    tradeDate: "20/07/2025",
    counterpartyCode: "RELIANCE",
    buySell: "BUY",
    commodity: "Diesel",
    grade: "Euro V",
    contractTerm: "Short",
    periodStartDate: "23/07/2025",
    periodEndDate: "28/07/2025",
    incoterm: "CFR",
    loadLocation: "JAMNAGAR",
    unloadLocation: "KOLKATA",
    priceType: "Fixed"
  },
  {
    tradeId: "DRAFT/5743",
    tradeDate: "21/07/2025",
    counterpartyCode: "BP_INDIA",
    buySell: "SELL",
    commodity: "Petrol",
    grade: "RON 95",
    contractTerm: "Long",
    periodStartDate: "01/08/2025",
    periodEndDate: "30/11/2025",
    incoterm: "EXW",
    loadLocation: "VISAKHAPATNAM",
    unloadLocation: "HYDERABAD",
    priceType: "Floating"
  },
  {
    tradeId: "DRAFT/5744",
    tradeDate: "22/07/2025",
    counterpartyCode: "TATA_OIL",
    buySell: "BUY",
    commodity: "Cooking Oil",
    grade: "Refined",
    contractTerm: "Medium",
    periodStartDate: "26/07/2025",
    periodEndDate: "10/10/2025",
    incoterm: "CIF",
    loadLocation: "MANGALORE",
    unloadLocation: "PUNE",
    priceType: "Fixed"
  },
  {
    tradeId: "DRAFT/5745/22-07-2025",
    tradeDate: "23/07/2025",
    counterpartyCode: "ADANI_GAS",
    buySell: "SELL",
    commodity: "LNG",
    grade: "Commercial",
    contractTerm: "Short",
    periodStartDate: "28/07/2025",
    periodEndDate: "05/08/2025",
    incoterm: "FOB",
    loadLocation: "KOCHI",
    unloadLocation: "BANGALORE",
    priceType: "Floating"
  },
  {
    tradeId: "DRAFT/5746",
    tradeDate: "24/07/2025",
    counterpartyCode: "IOC_LTD",
    buySell: "BUY",
    commodity: "Jet Fuel",
    grade: "ATF",
    contractTerm: "Long",
    periodStartDate: "02/08/2025",
    periodEndDate: "31/12/2025",
    incoterm: "DDU",
    loadLocation: "PANIPAT",
    unloadLocation: "GURGAON",
    priceType: "Fixed"
  },
  {
    tradeId: "DRAFT/5747",
    tradeDate: "25/07/2025",
    counterpartyCode: "ESSAR_OIL",
    buySell: "SELL",
    commodity: "Naphtha",
    grade: "Heavy",
    contractTerm: "Medium",
    periodStartDate: "30/07/2025",
    periodEndDate: "20/09/2025",
    incoterm: "CIP",
    loadLocation: "VADINAR",
    unloadLocation: "AHMEDABAD",
    priceType: "Floating"
  },
  {
    tradeId: "DRAFT/5748/22-07-2025",
    tradeDate: "26/07/2025",
    counterpartyCode: "ONGC_VID",
    buySell: "BUY",
    commodity: "Furnace Oil",
    grade: "180 CST",
    contractTerm: "Short",
    periodStartDate: "01/08/2025",
    periodEndDate: "10/08/2025",
    incoterm: "FAS",
    loadLocation: "ENNORE",
    unloadLocation: "TUTICORIN",
    priceType: "Fixed"
  },
  {
    tradeId: "DRAFT/5749/22-07-2025",
    tradeDate: "27/07/2025",
    counterpartyCode: "BHARAT_PET",
    buySell: "SELL",
    commodity: "Kerosene",
    grade: "Superior",
    contractTerm: "Long",
    periodStartDate: "05/08/2025",
    periodEndDate: "28/02/2026",
    incoterm: "DAP",
    loadLocation: "NUMALIGARH",
    unloadLocation: "GUWAHATI",
    priceType: "Floating"
  }
  ];
}